RULES_VERSION = "v1.0"

MAX_MEMBERCODE_LENGTH = 5
INVALID_PREFIXES = ("RG",)

STATUS_CONFIRMED = "CONFIRMED"
STATUS_CONFIRMED_2NAME = "CONFIRMED_2NAME"
STATUS_AMBIGUOUS = "AMBIGUOUS"
STATUS_POSITION_CSCS = "POSITION IN CSCS"
STATUS_MORE_THAN_5 = "MORE THAN 5"
STATUS_NOT_FOUND = "NOT FOUND"

STATUS_PRIORITY = {
    STATUS_CONFIRMED: 1,
    STATUS_CONFIRMED_2NAME: 2,
    STATUS_AMBIGUOUS: 3,
    STATUS_POSITION_CSCS: 4,
    STATUS_NOT_FOUND: 5,
    STATUS_MORE_THAN_5: 6,
}
